POST  http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
    "username" : "beamrookthat",
    "email" : "beamrockthai@gmail.com",
    "password" : "beam78895530TI"
}
# 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
//FULL
